name: psirt-bot-cards-dispatch

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [PSIRT_Run]
jobs:
  build:
    name: Run psirt-bot.py
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: psirt_bot_card_env
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install --upgrade dnspython
          pip install --upgrade pymongo
          pip install --upgrade certifi
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        env:
          mongouser: ${{ secrets.MONGOUSER }}
          mongopw: ${{ secrets.MONGOPW }}
          webex_bearer: ${{ secrets.WEBEX_BEARER }}
          psirt_client_id: ${{ secrets.PSIRT_CLIENT_ID }}
          psirt_client_secret: ${{ secrets.PSIRT_CLIENT_SECRET }}
          gsheet_doc_link_7: ${{secrets.GSHEET_DOC_LINK_7}}
          gsheet_doc_link_14: ${{secrets.GSHEET_DOC_LINK_14}}
          gsheet_doc_link_30: ${{secrets.GSHEET_DOC_LINK_30}}
        run: |
          python psirt-bot.py